### ISSUE TITLE
Could you share .env setup in readme please

### ISSUE THREAD

**Issue by zaletskyi** [jamesqquick/jqq-util-functions#1]
Hi James,

I really like to play around with netlify functions.
I'm wondering what repo should I use for sanity setup and env variables?

Thanks,
Michael

**Comment by jamesqquick** [comment]
So you're just looking for which variables are needed, and not asking specifically for my variables right? haha

**Comment by zaletskyi** [comment]
haha no I don't need your variables. I would to set my own environment and play around with it.

**Comment by jamesqquick** [comment]
Ok just making sure. I'm not actually using this repo anymore. I copied over functionality into my sanity project. Which functionality are you interested in specifically? Generation of cover images? Also, feel free to dm me on Twitter for an easier conversation!

**Comment by zaletskyi** [comment]
Ok thank I'll DM
